-- ─── Storage bucket ──────────────────────────────────────────────────────────
-- 500 MB per file limit; private bucket (no public access without signed URL)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'videos',
  'videos',
  false,
  524288000,
  array['video/mp4', 'video/quicktime', 'video/webm', 'audio/mpeg', 'audio/mp4']
)
on conflict (id) do nothing;

-- ─── Storage RLS policies ─────────────────────────────────────────────────────
-- Path convention inside the bucket: {workspace_id}/{video_id}/{filename}
-- The first path segment is always the workspace_id.
-- Backend uploads via service role (bypasses RLS).
-- Frontend downloads via signed URLs generated by the backend.

-- Workspace members can download files in their workspace
create policy "storage_workspace_read"
  on storage.objects for select
  to authenticated
  using (
    bucket_id = 'videos'
    and exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id::text = (string_to_array(storage.objects.name, '/'))[1]
        and wm.user_id = auth.uid()
    )
  );

-- Workspace members can upload files to their own workspace path
create policy "storage_workspace_insert"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'videos'
    and exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id::text = (string_to_array(storage.objects.name, '/'))[1]
        and wm.user_id = auth.uid()
    )
  );

-- Workspace admins can delete files
create policy "storage_workspace_delete"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'videos'
    and exists (
      select 1 from public.workspace_members wm
      where wm.workspace_id::text = (string_to_array(storage.objects.name, '/'))[1]
        and wm.user_id = auth.uid()
        and wm.role = 'admin'
    )
  );
